# Generated by Django 2.2 on 2019-05-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrant', '0002_auto_20190509_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='date_sr_obr',
            field=models.CharField(max_length=10),
        ),
    ]
