# Generated by Django 2.2 on 2019-05-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrant', '0003_auto_20190509_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='date_sr_obr',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='fio',
            field=models.CharField(max_length=20),
        ),
    ]
