# Generated by Django 2.2 on 2019-05-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrant', '0004_auto_20190510_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='date_sr_obr',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='fio',
            field=models.CharField(max_length=100),
        ),
    ]
